# --- !Ups
CREATE TABLE `CAT` (
	`ID` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`NAME` VARCHAR(100),
	`COLOR` VARCHAR(100),
	`ACTIVATE` BOOL NOT NULL DEFAULT '1'
);

CREATE TABLE `DOG` (
	`NAME` VARCHAR(100) NOT NULL PRIMARY KEY,
	`COLOR` VARCHAR(100)
);

# --- !Downs

drop table "CAT";
drop table "DOG";